# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget AsposeEmailConvertor)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target AsposeEmailConvertor
add_library(AsposeEmailConvertor SHARED IMPORTED)

set_target_properties(AsposeEmailConvertor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/project/ae.cpp/Examples/AsposeEmailConvertor/include"
)

# Import target "AsposeEmailConvertor" for configuration "Debug"
set_property(TARGET AsposeEmailConvertor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(AsposeEmailConvertor PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/Debug/AsposeEmailConvertor.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "Aspose.Email.Cpp;Aspose::CodePorting.Translator.Cs2Cpp.Framework"
  IMPORTED_LOCATION_DEBUG "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/Debug/AsposeEmailConvertor.dll"
  )

# Import target "AsposeEmailConvertor" for configuration "Release"
set_property(TARGET AsposeEmailConvertor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(AsposeEmailConvertor PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/Release/AsposeEmailConvertor.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "Aspose.Email.Cpp;Aspose::CodePorting.Translator.Cs2Cpp.Framework"
  IMPORTED_LOCATION_RELEASE "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/Release/AsposeEmailConvertor.dll"
  )

# Import target "AsposeEmailConvertor" for configuration "MinSizeRel"
set_property(TARGET AsposeEmailConvertor APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(AsposeEmailConvertor PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/MinSizeRel/AsposeEmailConvertor.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "Aspose.Email.Cpp;Aspose::CodePorting.Translator.Cs2Cpp.Framework"
  IMPORTED_LOCATION_MINSIZEREL "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/MinSizeRel/AsposeEmailConvertor.dll"
  )

# Import target "AsposeEmailConvertor" for configuration "RelWithDebInfo"
set_property(TARGET AsposeEmailConvertor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(AsposeEmailConvertor PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/RelWithDebInfo/AsposeEmailConvertor.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "Aspose.Email.Cpp;Aspose::CodePorting.Translator.Cs2Cpp.Framework"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/project/ae.cpp/Examples/AsposeEmailConvertor/build/RelWithDebInfo/AsposeEmailConvertor.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
