#pragma once

#include <cstdint>

#include <system/array.h>
#include <system/bit_converter.h>
#include <system/collections/icollection.h>
#include <system/collections/ienumerable.h>
#include <system/collections/ienumerator.h>
#include <system/collections/ilist.h>
#include <system/collections/list.h>
#include <system/collections/specialized/string_dictionary.h>
#include <system/console.h>
#include <system/convert.h>
#include <system/date_time.h>
#include <system/decimal.h>
#include <system/details/dispose_guard.h>
#include <system/enum_helpers.h>
#include <system/environment.h>
#include <system/exceptions.h>
#include <system/guid.h>
#include <system/io/directory.h>
#include <system/io/directory_info.h>
#include <system/io/file.h>
#include <system/io/file_access.h>
#include <system/io/file_mode.h>
#include <system/io/file_stream.h>
#include <system/io/memory_stream.h>
#include <system/io/path.h>
#include <system/io/seekorigin.h>
#include <system/io/stream.h>
#include <system/nullable.h>
#include <system/object.h>
#include <system/object_ext.h>
#include <system/setters_wrap.h>
#include <system/shared_ptr.h>
#include <system/special_casts.h>
#include <system/string.h>
#include <system/string_comparison.h>
#include <system/text/encoding.h>
#include <system/timespan.h>
#include <system/timezone.h>
#include <system/timezone_info.h>
#include <system/uri.h>

#include <AlternateView.h>
#include <AlternateViewCollection.h>
#include <AntiSpam/SpamAnalyzer.h>
#include <Attachment.h>
#include <AttachmentCollection.h>
#include <Bounce/BounceResult.h>
#include <Bounce/DSNAction.h>
#include <Calendar/Appointment.h>
#include <Calendar/AppointmentMethodType.h>
#include <Calendar/AppointmentReminder.h>
#include <Calendar/AppointmentReminderCollection.h>
#include <Calendar/AppointmentSaveFormat.h>
#include <Calendar/CalendarReader.h>
#include <Calendar/Recurrences/CalendarRecurrence.h>
#include <Calendar/Recurrences/DateCollection.h>
#include <Calendar/ReminderAction.h>
#include <Calendar/ReminderAttachment.h>
#include <Calendar/ReminderAttachmentCollection.h>
#include <Calendar/ReminderAttendee.h>
#include <Calendar/ReminderAttendeeCollection.h>
#include <Calendar/ReminderDuration.h>
#include <Calendar/ReminderRelated.h>
#include <Calendar/ReminderTrigger.h>
#include <ContactFieldsSet.h>
#include <DeliveryNotificationOptions.h>
#include <EmlLoadOptions.h>
#include <EmlSaveOptions.h>
#include <FileCompatibilityMode.h>
#include <HtmlLoadOptions.h>
#include <Licensing/License.h>
#include <LinkedResource.h>
#include <LinkedResourceCollection.h>
#include <MailAddress.h>
#include <MailAddressCollection.h>
#include <MailMessage.h>
#include <MailMessageSaveType.h>
#include <MailPriority.h>
#include <MailSensitivity.h>
#include <Mapi/BodyContentType.h>
#include <Mapi/ContactSaveFormat.h>
#include <Mapi/FollowUpManager.h>
#include <Mapi/FollowUpOptions.h>
#include <Mapi/IMapiMessageItem.h>
#include <Mapi/MailConversionOptions.h>
#include <Mapi/MapiAttachment.h>
#include <Mapi/MapiAttachmentCollection.h>
#include <Mapi/MapiCalendar.h>
#include <Mapi/MapiCalendarDailyRecurrencePattern.h>
#include <Mapi/MapiCalendarDayOfWeek.h>
#include <Mapi/MapiCalendarEventRecurrence.h>
#include <Mapi/MapiCalendarExceptionInfo.h>
#include <Mapi/MapiCalendarMonthlyRecurrencePattern.h>
#include <Mapi/MapiCalendarRecurrenceEndType.h>
#include <Mapi/MapiCalendarRecurrencePattern.h>
#include <Mapi/MapiCalendarRecurrencePatternFactory.h>
#include <Mapi/MapiCalendarRecurrencePatternType.h>
#include <Mapi/MapiCalendarTimeZone.h>
#include <Mapi/MapiCalendarWeeklyRecurrencePattern.h>
#include <Mapi/MapiContact.h>
#include <Mapi/MapiContactElectronicAddress.h>
#include <Mapi/MapiContactElectronicAddressPropertySet.h>
#include <Mapi/MapiContactGender.h>
#include <Mapi/MapiContactNamePropertySet.h>
#include <Mapi/MapiContactOtherPropertySet.h>
#include <Mapi/MapiContactPersonalInfoPropertySet.h>
#include <Mapi/MapiContactPhoto.h>
#include <Mapi/MapiContactPhotoImageFormat.h>
#include <Mapi/MapiContactPhysicalAddress.h>
#include <Mapi/MapiContactPhysicalAddressPropertySet.h>
#include <Mapi/MapiContactProfessionalPropertySet.h>
#include <Mapi/MapiContactTelephonePropertySet.h>
#include <Mapi/MapiConversionOptions.h>
#include <Mapi/MapiDistributionList.h>
#include <Mapi/MapiDistributionListEntryIdType.h>
#include <Mapi/MapiDistributionListMember.h>
#include <Mapi/MapiDistributionListMemberCollection.h>
#include <Mapi/MapiJournal.h>
#include <Mapi/MapiMessage.h>
#include <Mapi/MapiMessageFlags.h>
#include <Mapi/MapiMessageItemBase.h>
#include <Mapi/MapiNamedProperty.h>
#include <Mapi/MapiNamedPropertyMappingStorage.h>
#include <Mapi/MapiNote.h>
#include <Mapi/MapiObjectProperty.h>
#include <Mapi/MapiProperty.h>
#include <Mapi/MapiPropertyCollection.h>
#include <Mapi/MapiPropertyContainer.h>
#include <Mapi/MapiPropertyTag.h>
#include <Mapi/MapiPropertyType.h>
#include <Mapi/MapiRecipient.h>
#include <Mapi/MapiRecipientCollection.h>
#include <Mapi/MapiRecipientTrackStatus.h>
#include <Mapi/MapiRecipientType.h>
#include <Mapi/MapiTask.h>
#include <Mapi/MapiTaskHistory.h>
#include <Mapi/MapiTaskOwnership.h>
#include <Mapi/MapiTaskState.h>
#include <Mapi/MapiTaskStatus.h>
#include <Mapi/MapiTaskUsers.h>
#include <Mapi/NoteColor.h>
#include <Mapi/NoteSaveFormat.h>
#include <Mapi/OutlookMessageFormat.h>
#include <Mapi/TaskSaveFormat.h>
#include <MhtFormatOptions.h>
#include <MhtmlLoadOptions.h>
#include <MhtSaveOptions.h>
#include <MhtTemplateName.h>
#include <Mime/ContentType.h>
#include <Mime/HeaderCollection.h>
#include <Mime/MediaTypeNames.h>
#include <MsgLoadOptions.h>
#include <MsgSaveOptions.h>
#include <ParticipationStatus.h>
#include <PersonalInfo/VCard/VCardContact.h>
#include <SaveOptions.h>
#include <Storage/Pst/FileFormat.h>
#include <Storage/Pst/FileFormatVersion.h>
#include <Storage/Pst/FolderInfo.h>
#include <Storage/Pst/FolderInfoCollection.h>
#include <Storage/Pst/FolderKind.h>
#include <Storage/Pst/ItemMovedEventArgs.h>
#include <Storage/Pst/MapiImportance.h>
#include <Storage/Pst/MapiSensitivity.h>
#include <Storage/Pst/MessageAddedEventArgs.h>
#include <Storage/Pst/MessageInfo.h>
#include <Storage/Pst/MessageInfoCollection.h>
#include <Storage/Pst/MessageStore.h>
#include <Storage/Pst/PersonalStorage.h>
#include <Storage/Pst/PersonalStorageQueryBuilder.h>
#include <Storage/Pst/StandardIpmFolder.h>
#include <Storage/Pst/StorageProcessedEventArgs.h>
#include <Tools/FileFormat/FileFormatInfo.h>
#include <Tools/FileFormat/FileFormatType.h>
#include <Tools/FileFormat/FileFormatUtil.h>
#include <Tools/ResponseMessageBuilder/ForwardMessageBuilder.h>
#include <Tools/ResponseMessageBuilder/OriginalMessageAdditionMode.h>
#include <Tools/ResponseMessageBuilder/ReplyMessageBuilder.h>
#include <Tools/Search/DateComparisonField.h>
#include <Tools/Search/IntComparisonField.h>
#include <Tools/Search/MailQuery.h>
#include <Tools/Search/StringComparisonField.h>
